FROM ruby:3.4.5-slim

WORKDIR /rails

ENV RAILS_ENV=development \
    DEBIAN_FRONTEND=noninteractive

# Install packages for dev (includes compilers)
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    build-essential \
    git \
    curl \
    nodejs \
    yarn \
    postgresql-client \
    libpq-dev \
    libvips42 && \
    rm -rf /var/lib/apt/lists/*

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]
