name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ variables.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ variables.DOCKER_HUB_USERNAME }}/cte412miniproject:latest
            ${{ variables.DOCKER_HUB_USERNAME }}/cte412miniproject:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output image info
        id: image-info
        run: |
          echo "image=${{ variables.DOCKER_HUB_USERNAME }}/cte412miniproject:${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "Docker image built and pushed successfully."
