name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_HUB_USERNAME }}/cte412miniproject:latest
            ${{ vars.DOCKER_HUB_USERNAME }}/cte412miniproject:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate CD Summary
        if: always()
        run: |
          echo "### 🚀 CD Pipeline Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Image:** ${{ vars.DOCKER_HUB_USERNAME }}/cte412miniproject" >> $GITHUB_STEP_SUMMARY
          echo "- **Tags:** latest, ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Status:** ✅ Successful" >> $GITHUB_STEP_SUMMARY
          echo "- **Triggered by:** CI Pipeline completion" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "🎉 The image has been successfully built and pushed to Docker Hub!" >> $GITHUB_STEP_SUMMARY
